language: node_js
node_js:
  - "10.16.3"
  - "node"
script:
  - echo "Deploying!"
install:
  - npm i -g firebase-tools @vue/cli
  - npm i
after_success:
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
